dist: trusty

language: python

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: RUN=unit
    - python: 3.5
      env:
        - RUN=unit COVERALLS=true
    - python: 3.5
      env: RUN=pep8
    - python: 3.5
      env: RUN=docs

install:
  - if [ "${RUN}" != "pep8" ]; then
      yes | sudo add-apt-repository ppa:zoogie/sdl2-snapshots;
      yes | sudo add-apt-repository ppa:gstreamer-developers/ppa;
      sudo apt-get update;
      sudo apt-get -y install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev;
      sudo apt-get -y install libgstreamer1.0-dev gstreamer1.0-alsa gstreamer1.0-plugins-base;
      sudo apt-get -y install python-dev libsmpeg-dev libswscale-dev libavformat-dev libavcodec-dev libjpeg-dev libtiff4-dev libX11-dev libmtdev-dev;
      sudo apt-get -y install python-setuptools build-essential libgl1-mesa-dev libgles2-mesa-dev;
      sudo apt-get -y install xvfb pulseaudio;
      pip install --upgrade cython pillow nose coveralls;
    fi;
  - if [ "${RUN}" == "docs" ]; then
      sudo apt-get -y install texlive-full;
      pip install --upgrade sphinxcontrib-blockdiag sphinxcontrib-seqdiag sphinxcontrib-actdiag sphinxcontrib-nwdiag;
    fi;

before_script:
  - if [ "${RUN}" != "pep8" ]; then
      export DISPLAY=:99.0;
      /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX;
      export PYTHONPATH=$PYTHONPATH:$(pwd);
    fi;

script:
  - set -v
  - if [ "${RUN}" == "unit" ]; then
      make;
      make test;
    fi;
  - if [ "${COVERALLS}" == "true" ] && [ "${TRAVIS_BRANCH}" == "master" ]; then
      coveralls;
    fi;
  - if [ "${RUN}" == "pep8" ]; then
      make style;
    fi;
  - if [ "${RUN}" == "docs" ]; then
      make html;
      make pdf || true;
      make pdf;
    fi;

after_success:
  - if [ "${RUN}" == "docs" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${TRAVIS_BRANCH}" == "master" ]; then
      openssl aes-256-cbc -K $encrypted_675f1a0c317c_key -iv $encrypted_675f1a0c317c_iv -in ./kivy/tools/travis/id_rsa.enc -out ~/.ssh/id_rsa -d;
      chmod 600 ~/.ssh/id_rsa;
      echo -e "Host kivy.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config;
      rsync --delete --force -r -e ssh ./doc/build/html/ kivy@kivy.org:~/kivy.org/docs/api-trunk/;
      mv ./doc/build/latex/Kivy.pdf ./doc/build/latex/Kivy-latest.pdf;
      rsync -e ssh ./doc/build/latex/Kivy-latest.pdf kivy@kivy.org:~/kivy.org/docs/pdf/Kivy-latest.pdf;
    fi;

notifications:
  webhooks:
    urls:
      - http://kivy.org:5000/travisevent
    on_success: always
    on_failure: always
    on_start: always
